// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: seo_setting.
// - Entity ID: 102019bad36f5bc7648b3c1805bf4fcef9a.
// - Entity Version: 102019bad36f5bc7109b99a8929ec378011.
// - Task ID: 6963a39127dae773f88ecfb3.
// - Task Root ID: 6963a39127dae773f88ecfb3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for SeoSettingModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SeoSettingModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  setting_key: string;
  site_title: string;
  meta_description: string;
  og_title: string;
  og_description: string;
  og_image_url: string;
  canonical_url: string;
  twitter_handle?: string | null;
}

/**
 * ORM class for SeoSetting entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SeoSettingORM {
  private static instance: SeoSettingORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019bad36f5bc7648b3c1805bf4fcef9a';
    this.entityName = 'seo_setting';
    this.entityVersion = '102019bad36f5bc7109b99a8929ec378011';
    this.taskId = '6963a39127dae773f88ecfb3';
    this.taskRootId = '6963a39127dae773f88ecfb3';
  }

  /**
   * Get singleton instance of SeoSettingORM
   */
  public static getInstance(): SeoSettingORM {
    if (!SeoSettingORM.instance) {
      SeoSettingORM.instance = new SeoSettingORM();
    }
    
    return SeoSettingORM.instance;
  }

  /**
   * Get seo_setting by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getSeoSettingByIDs(ids: string[]): Promise<SeoSettingModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete seo_setting by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteSeoSettingByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all SeoSetting records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSeoSetting(): Promise<SeoSettingModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new SeoSetting record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSeoSetting(data: SeoSettingModel[]): Promise<SeoSettingModel[]> {
    const structured = data.map((item) => CreateData(SeoSettingModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all SeoSetting records
   */
  async purgeAllSeoSetting(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List SeoSetting records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSeoSetting(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SeoSettingModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get seo_setting by Id index
   * This function gets data by index.
   */
  async getSeoSettingById(
    id: string,
  ): Promise<SeoSettingModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) seo_setting by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSeoSettingById(
    id: string,
    data: SeoSettingModel
  ): Promise<SeoSettingModel[]> {
    const index = createIndexId(
      id
    );

    const values = SeoSettingModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete seo_setting by Id index
   */
  async deleteSeoSettingById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get seo_setting by DataCreator index
   * This function gets data by index.
   */
  async getSeoSettingByDataCreator(
    data_creator: string,
  ): Promise<SeoSettingModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) seo_setting by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSeoSettingByDataCreator(
    data_creator: string,
    data: SeoSettingModel
  ): Promise<SeoSettingModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SeoSettingModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete seo_setting by DataCreator index
   */
  async deleteSeoSettingByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get seo_setting by DataUpdater index
   * This function gets data by index.
   */
  async getSeoSettingByDataUpdater(
    data_updater: string,
  ): Promise<SeoSettingModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) seo_setting by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSeoSettingByDataUpdater(
    data_updater: string,
    data: SeoSettingModel
  ): Promise<SeoSettingModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SeoSettingModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete seo_setting by DataUpdater index
   */
  async deleteSeoSettingByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get seo_setting by SettingKey index
   * This function gets data by index.
   */
  async getSeoSettingBySettingKey(
    setting_key: string,
  ): Promise<SeoSettingModel[]> {
    const index = createIndexSettingKey(
      setting_key
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) seo_setting by SettingKey index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSeoSettingBySettingKey(
    setting_key: string,
    data: SeoSettingModel
  ): Promise<SeoSettingModel[]> {
    const index = createIndexSettingKey(
      setting_key
    );

    const values = SeoSettingModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete seo_setting by SettingKey index
   */
  async deleteSeoSettingBySettingKey(
    setting_key: string
  ): Promise<void> {
    const index = createIndexSettingKey(
      setting_key
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SeoSettingModel data array
   */
  private resultToData(values: Data[]): SeoSettingModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SeoSettingModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SeoSettingModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SeoSettingModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SeoSettingModel => item !== null);
  }
}

/**
 * Convert SeoSettingModel data to Value array
 */
function SeoSettingModelToValues(data: SeoSettingModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'setting_key', type: DataType.string, defaultValue: '' },
    { key: 'site_title', type: DataType.string, defaultValue: '' },
    { key: 'meta_description', type: DataType.string, defaultValue: '' },
    { key: 'og_title', type: DataType.string, defaultValue: '' },
    { key: 'og_description', type: DataType.string, defaultValue: '' },
    { key: 'og_image_url', type: DataType.string, defaultValue: '' },
    { key: 'canonical_url', type: DataType.string, defaultValue: '' },
    { key: 'twitter_handle', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SeoSettingModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SeoSettingModel data
 */
function SeoSettingModelFromValues(values: Value[]): SeoSettingModel {
  const data: Partial<SeoSettingModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'setting_key':
        data.setting_key = ParseValue(value, DataType.string) as string;
        break;
      case 'site_title':
        data.site_title = ParseValue(value, DataType.string) as string;
        break;
      case 'meta_description':
        data.meta_description = ParseValue(value, DataType.string) as string;
        break;
      case 'og_title':
        data.og_title = ParseValue(value, DataType.string) as string;
        break;
      case 'og_description':
        data.og_description = ParseValue(value, DataType.string) as string;
        break;
      case 'og_image_url':
        data.og_image_url = ParseValue(value, DataType.string) as string;
        break;
      case 'canonical_url':
        data.canonical_url = ParseValue(value, DataType.string) as string;
        break;
      case 'twitter_handle':
        data.twitter_handle = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as SeoSettingModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for SettingKey fields
 */
function createIndexSettingKey(
  setting_key: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, setting_key, 'setting_key'),
  ];

  return {
    fields: ['setting_key'],
    values
  };
}

export default SeoSettingORM;