// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: admin_session.
// - Entity ID: 102019bad36f5bc723490fae3ed7c40cb81.
// - Entity Version: 102019bad36f5bc7109b99a8929ec378011.
// - Task ID: 6963a39127dae773f88ecfb3.
// - Task Root ID: 6963a39127dae773f88ecfb3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for AdminSessionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface AdminSessionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  session_token: string;
  expires_at: string;
  user_id: string;
}

/**
 * ORM class for AdminSession entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class AdminSessionORM {
  private static instance: AdminSessionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019bad36f5bc723490fae3ed7c40cb81';
    this.entityName = 'admin_session';
    this.entityVersion = '102019bad36f5bc7109b99a8929ec378011';
    this.taskId = '6963a39127dae773f88ecfb3';
    this.taskRootId = '6963a39127dae773f88ecfb3';
  }

  /**
   * Get singleton instance of AdminSessionORM
   */
  public static getInstance(): AdminSessionORM {
    if (!AdminSessionORM.instance) {
      AdminSessionORM.instance = new AdminSessionORM();
    }
    
    return AdminSessionORM.instance;
  }

  /**
   * Get admin_session by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getAdminSessionByIDs(ids: string[]): Promise<AdminSessionModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_session by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteAdminSessionByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all AdminSession records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllAdminSession(): Promise<AdminSessionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new AdminSession record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertAdminSession(data: AdminSessionModel[]): Promise<AdminSessionModel[]> {
    const structured = data.map((item) => CreateData(AdminSessionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all AdminSession records
   */
  async purgeAllAdminSession(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List AdminSession records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listAdminSession(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[AdminSessionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get admin_session by Id index
   * This function gets data by index.
   */
  async getAdminSessionById(
    id: string,
  ): Promise<AdminSessionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_session by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminSessionById(
    id: string,
    data: AdminSessionModel
  ): Promise<AdminSessionModel[]> {
    const index = createIndexId(
      id
    );

    const values = AdminSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_session by Id index
   */
  async deleteAdminSessionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_session by DataCreator index
   * This function gets data by index.
   */
  async getAdminSessionByDataCreator(
    data_creator: string,
  ): Promise<AdminSessionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_session by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminSessionByDataCreator(
    data_creator: string,
    data: AdminSessionModel
  ): Promise<AdminSessionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = AdminSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_session by DataCreator index
   */
  async deleteAdminSessionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_session by DataUpdater index
   * This function gets data by index.
   */
  async getAdminSessionByDataUpdater(
    data_updater: string,
  ): Promise<AdminSessionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_session by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminSessionByDataUpdater(
    data_updater: string,
    data: AdminSessionModel
  ): Promise<AdminSessionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = AdminSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_session by DataUpdater index
   */
  async deleteAdminSessionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_session by SessionToken index
   * This function gets data by index.
   */
  async getAdminSessionBySessionToken(
    session_token: string,
  ): Promise<AdminSessionModel[]> {
    const index = createIndexSessionToken(
      session_token
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_session by SessionToken index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminSessionBySessionToken(
    session_token: string,
    data: AdminSessionModel
  ): Promise<AdminSessionModel[]> {
    const index = createIndexSessionToken(
      session_token
    );

    const values = AdminSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_session by SessionToken index
   */
  async deleteAdminSessionBySessionToken(
    session_token: string
  ): Promise<void> {
    const index = createIndexSessionToken(
      session_token
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_session by ExpiresAt index
   * This function gets data by index.
   */
  async getAdminSessionByExpiresAt(
    expires_at: string,
  ): Promise<AdminSessionModel[]> {
    const index = createIndexExpiresAt(
      expires_at
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_session by ExpiresAt index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminSessionByExpiresAt(
    expires_at: string,
    data: AdminSessionModel
  ): Promise<AdminSessionModel[]> {
    const index = createIndexExpiresAt(
      expires_at
    );

    const values = AdminSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_session by ExpiresAt index
   */
  async deleteAdminSessionByExpiresAt(
    expires_at: string
  ): Promise<void> {
    const index = createIndexExpiresAt(
      expires_at
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_session by UserId index
   * This function gets data by index.
   */
  async getAdminSessionByUserId(
    user_id: string,
  ): Promise<AdminSessionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_session by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminSessionByUserId(
    user_id: string,
    data: AdminSessionModel
  ): Promise<AdminSessionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = AdminSessionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_session by UserId index
   */
  async deleteAdminSessionByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to AdminSessionModel data array
   */
  private resultToData(values: Data[]): AdminSessionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return AdminSessionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as AdminSessionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized AdminSessionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is AdminSessionModel => item !== null);
  }
}

/**
 * Convert AdminSessionModel data to Value array
 */
function AdminSessionModelToValues(data: AdminSessionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'session_token', type: DataType.string, defaultValue: '' },
    { key: 'expires_at', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof AdminSessionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to AdminSessionModel data
 */
function AdminSessionModelFromValues(values: Value[]): AdminSessionModel {
  const data: Partial<AdminSessionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'session_token':
        data.session_token = ParseValue(value, DataType.string) as string;
        break;
      case 'expires_at':
        data.expires_at = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as AdminSessionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for SessionToken fields
 */
function createIndexSessionToken(
  session_token: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, session_token, 'session_token'),
  ];

  return {
    fields: ['session_token'],
    values
  };
}
/**
 * Create index for ExpiresAt fields
 */
function createIndexExpiresAt(
  expires_at: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, expires_at, 'expires_at'),
  ];

  return {
    fields: ['expires_at'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}

export default AdminSessionORM;