// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: petition_signature.
// - Entity ID: 102019bad36f5bc74728894ab600dad13d1.
// - Entity Version: 102019bad36f5bc7109b99a8929ec378011.
// - Task ID: 6963a39127dae773f88ecfb3.
// - Task Root ID: 6963a39127dae773f88ecfb3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for PetitionSignatureModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PetitionSignatureModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  name: string;
  email: string;
  postcode: string;
  comment?: string | null;
  consent: boolean;
}

/**
 * ORM class for PetitionSignature entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PetitionSignatureORM {
  private static instance: PetitionSignatureORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019bad36f5bc74728894ab600dad13d1';
    this.entityName = 'petition_signature';
    this.entityVersion = '102019bad36f5bc7109b99a8929ec378011';
    this.taskId = '6963a39127dae773f88ecfb3';
    this.taskRootId = '6963a39127dae773f88ecfb3';
  }

  /**
   * Get singleton instance of PetitionSignatureORM
   */
  public static getInstance(): PetitionSignatureORM {
    if (!PetitionSignatureORM.instance) {
      PetitionSignatureORM.instance = new PetitionSignatureORM();
    }
    
    return PetitionSignatureORM.instance;
  }

  /**
   * Get petition_signature by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getPetitionSignatureByIDs(ids: string[]): Promise<PetitionSignatureModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete petition_signature by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deletePetitionSignatureByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all PetitionSignature records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPetitionSignature(): Promise<PetitionSignatureModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new PetitionSignature record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPetitionSignature(data: PetitionSignatureModel[]): Promise<PetitionSignatureModel[]> {
    const structured = data.map((item) => CreateData(PetitionSignatureModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all PetitionSignature records
   */
  async purgeAllPetitionSignature(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List PetitionSignature records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPetitionSignature(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PetitionSignatureModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get petition_signature by Id index
   * This function gets data by index.
   */
  async getPetitionSignatureById(
    id: string,
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) petition_signature by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPetitionSignatureById(
    id: string,
    data: PetitionSignatureModel
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexId(
      id
    );

    const values = PetitionSignatureModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete petition_signature by Id index
   */
  async deletePetitionSignatureById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get petition_signature by DataCreator index
   * This function gets data by index.
   */
  async getPetitionSignatureByDataCreator(
    data_creator: string,
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) petition_signature by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPetitionSignatureByDataCreator(
    data_creator: string,
    data: PetitionSignatureModel
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PetitionSignatureModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete petition_signature by DataCreator index
   */
  async deletePetitionSignatureByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get petition_signature by DataUpdater index
   * This function gets data by index.
   */
  async getPetitionSignatureByDataUpdater(
    data_updater: string,
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) petition_signature by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPetitionSignatureByDataUpdater(
    data_updater: string,
    data: PetitionSignatureModel
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PetitionSignatureModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete petition_signature by DataUpdater index
   */
  async deletePetitionSignatureByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get petition_signature by Email index
   * This function gets data by index.
   */
  async getPetitionSignatureByEmail(
    email: string,
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) petition_signature by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPetitionSignatureByEmail(
    email: string,
    data: PetitionSignatureModel
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = PetitionSignatureModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete petition_signature by Email index
   */
  async deletePetitionSignatureByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get petition_signature by Postcode index
   * This function gets data by index.
   */
  async getPetitionSignatureByPostcode(
    postcode: string,
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexPostcode(
      postcode
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) petition_signature by Postcode index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPetitionSignatureByPostcode(
    postcode: string,
    data: PetitionSignatureModel
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexPostcode(
      postcode
    );

    const values = PetitionSignatureModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete petition_signature by Postcode index
   */
  async deletePetitionSignatureByPostcode(
    postcode: string
  ): Promise<void> {
    const index = createIndexPostcode(
      postcode
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get petition_signature by CreateTime index
   * This function gets data by index.
   */
  async getPetitionSignatureByCreateTime(
    create_time: string,
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) petition_signature by CreateTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPetitionSignatureByCreateTime(
    create_time: string,
    data: PetitionSignatureModel
  ): Promise<PetitionSignatureModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const values = PetitionSignatureModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete petition_signature by CreateTime index
   */
  async deletePetitionSignatureByCreateTime(
    create_time: string
  ): Promise<void> {
    const index = createIndexCreateTime(
      create_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PetitionSignatureModel data array
   */
  private resultToData(values: Data[]): PetitionSignatureModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PetitionSignatureModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PetitionSignatureModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PetitionSignatureModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PetitionSignatureModel => item !== null);
  }
}

/**
 * Convert PetitionSignatureModel data to Value array
 */
function PetitionSignatureModelToValues(data: PetitionSignatureModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'name', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'postcode', type: DataType.string, defaultValue: '' },
    { key: 'comment', type: DataType.string, defaultValue: null },
    { key: 'consent', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PetitionSignatureModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PetitionSignatureModel data
 */
function PetitionSignatureModelFromValues(values: Value[]): PetitionSignatureModel {
  const data: Partial<PetitionSignatureModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'name':
        data.name = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'postcode':
        data.postcode = ParseValue(value, DataType.string) as string;
        break;
      case 'comment':
        data.comment = ParseValue(value, DataType.string) as string | null;
        break;
      case 'consent':
        data.consent = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as PetitionSignatureModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for Postcode fields
 */
function createIndexPostcode(
  postcode: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, postcode, 'postcode'),
  ];

  return {
    fields: ['postcode'],
    values
  };
}
/**
 * Create index for CreateTime fields
 */
function createIndexCreateTime(
  create_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
  ];

  return {
    fields: ['create_time'],
    values
  };
}

export default PetitionSignatureORM;